<?php if(app()->getLocale() == 'ar'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-ar_AR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'bg'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-bg_BG.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'cs'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-cs_CZ.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'da'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-da_DK.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'de'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-de_DE.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'en'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-en_US.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'es'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-es_ES.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'et'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-et_EE.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'fa'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-fa_IR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'fi'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-fi_FI.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'fr'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-fr_FR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'hr'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-hr_HR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'hu'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-hu_HU.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'id'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-id_ID.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'it'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-it_IT.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'ja'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-ja_JP.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'ko'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-ko_KR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'lt'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-lt_LT.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'lv'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-lv_LV.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'nl'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-nl_NL.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'pl'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-pl_PL.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'pt-br'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-pt_BR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'ro'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-ro_RO.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'ru'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-ru_RU.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'sk'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-sk_SK.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'sl'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-sl_SI.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'sr'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-sr_SP.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'sv'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-sv_SE.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'th'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-th_TH.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'tr'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-tr_TR.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'vi'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-vi_VN.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'zh-CN'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-zh_CN.js')); ?>"></script>
<?php elseif(app()->getLocale() == 'zh-TW'): ?>
    <script src="<?php echo e(asset('frontend/vendor/bootstrap-select/i18n/defaults-zh_TW.js')); ?>"></script>
<?php endif; ?>
<?php /**PATH /home/runcloud/webapps/PestControlGoogleMap/laravel_project/resources/views/frontend/partials/bootstrap-select-locale.blade.php ENDPATH**/ ?>